/**
 * Default RBAC seed data. IDs are stable so migrations and re-seeds stay idempotent.
 */
export const DEFAULT_PERMISSIONS = [
  { id: "perm_user_create", resource: "user", action: "create", description: "Create users" },
  { id: "perm_user_list", resource: "user", action: "list", description: "List users" },
  { id: "perm_user_get", resource: "user", action: "get", description: "View user details" },
  { id: "perm_user_update", resource: "user", action: "update", description: "Update users" },
  { id: "perm_user_delete", resource: "user", action: "delete", description: "Delete users" },
  { id: "perm_user_set_role", resource: "user", action: "set-role", description: "Change user roles" },
  { id: "perm_user_ban", resource: "user", action: "ban", description: "Ban users" },
  { id: "perm_user_impersonate", resource: "user", action: "impersonate", description: "Impersonate users" },
  {
    id: "perm_user_impersonate_admins",
    resource: "user",
    action: "impersonate-admins",
    description: "Impersonate admin users",
  },
  { id: "perm_user_set_password", resource: "user", action: "set-password", description: "Set user passwords" },
  { id: "perm_session_list", resource: "session", action: "list", description: "List sessions" },
  { id: "perm_session_revoke", resource: "session", action: "revoke", description: "Revoke a session" },
  { id: "perm_session_delete", resource: "session", action: "delete", description: "Delete sessions" },
  { id: "perm_todo_create", resource: "todo", action: "create", description: "Create todos" },
  { id: "perm_todo_read", resource: "todo", action: "read", description: "Read todos" },
  { id: "perm_todo_update", resource: "todo", action: "update", description: "Update todos" },
  { id: "perm_todo_delete", resource: "todo", action: "delete", description: "Delete todos" },
  { id: "perm_todo_list", resource: "todo", action: "list", description: "List todos" },
  { id: "perm_settings_read", resource: "settings", action: "read", description: "Read settings" },
  { id: "perm_settings_update", resource: "settings", action: "update", description: "Update settings" },
  { id: "perm_role_create", resource: "role", action: "create", description: "Create roles" },
  { id: "perm_role_list", resource: "role", action: "list", description: "List roles" },
  { id: "perm_role_get", resource: "role", action: "get", description: "View role details" },
  { id: "perm_role_update", resource: "role", action: "update", description: "Update roles" },
  { id: "perm_role_delete", resource: "role", action: "delete", description: "Delete roles" },
  {
    id: "perm_permission_list",
    resource: "permission",
    action: "list",
    description: "List permissions",
  },
  {
    id: "perm_permission_assign",
    resource: "permission",
    action: "assign",
    description: "Assign permissions to roles",
  },
] as const;

export const DEFAULT_ROLES = [
  {
    id: "role_admin",
    name: "admin",
    displayName: "Administrator",
    description: "Full system access",
    isSystem: true,
  },
  {
    id: "role_manager",
    name: "manager",
    displayName: "Manager",
    description: "Manage users and application data",
    isSystem: true,
  },
  {
    id: "role_user",
    name: "user",
    displayName: "User",
    description: "Standard application user",
    isSystem: true,
  },
  {
    id: "role_viewer",
    name: "viewer",
    displayName: "Viewer",
    description: "Read-only access",
    isSystem: true,
  },
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: DEFAULT_PERMISSIONS.map((p) => p.id),
  manager: [
    "perm_user_list",
    "perm_user_get",
    "perm_user_update",
    "perm_session_list",
    "perm_todo_create",
    "perm_todo_read",
    "perm_todo_update",
    "perm_todo_delete",
    "perm_todo_list",
    "perm_settings_read",
    "perm_role_list",
    "perm_permission_list",
  ],
  user: [
    "perm_todo_create",
    "perm_todo_read",
    "perm_todo_update",
    "perm_todo_delete",
    "perm_todo_list",
    "perm_settings_read",
  ],
  viewer: ["perm_todo_read", "perm_todo_list", "perm_settings_read"],
};
